# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title
relative_permalinks: false

# Setup
title:            Eric Davidson
tagline:          'A software engineer'
description:      "A software engineer, writer, and game developer that won't stop making things"
url:              https://www.erdavids.com
baseurl:          /



paginate:         5



github:
  repo:           https://github.com/erdavids/portfolio
  gen-art:        https://github.com/erdavids/Generative-Art
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
