# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:title
relative_permalinks: false

# Setup
title:            Eric Davidson
tagline:          'A software engineer'
description:      "A software engineer that writes a lot about making things"
url:              https://www.erdavids.com
baseurl:          /
main_image:       ./preview.png

author:
  name: Eric Davidson
  twitter: thebuffed

twitter:
  username: thebuffed
  card: summary_large_image

social:
  name: Eric Davidson
  links:
    - https://twitter.com/thebuffed



paginate:         7



github:
  repo:           https://github.com/erdavids/portfolio
  gen-art:        https://github.com/erdavids/Generative-Art

projects:
  hex-map:        https://erdavids.com/hex-map
  first-line-api: https://www.firstlineapi.com/
  youtube:        https://www.youtube.com/channel/UCUrmX3SvpPerq-KAfGBrgGQ
  games:          https://thebuffed.itch.io/
  crochet-app:    https://play.google.com/store/apps/details?id=com.buffed.stitch&hl=en_US&gl=US

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
